### ISSUE TITLE
Implement weather API

### ISSUE THREAD

**Issue by nbice** [nbice/CEG4981#5]
# Task
Weather.com will be referenced for weather tracking. Implement the API in the Android app.

**Comment by GrubeCube** [comment]
Do we want to query the GPS location on the AUGER device or the mobile phone?

**Mobile Phone:**
_Pros:_
- We can routinely check weather forecasts when the app starts or with a daemon
- The code for parsing and checking the forecast will already be on the phone
- Does not require communication to be set up to get a fully working module

_Cons:_
- Phone is a personal device, so could be taken anywhere; therefore, we could be unnecessarily warning the user
- Daemon will take slightly more work and research

**AUGER Device**
_Pros:_
- Will get accurate weather forecasting with GPS coordinates because the device will stay in the same local area (probably)
- Can routinely check weather forecasts as a separate process or within a update loop
- Spawning a new process does not require additional research and should be straight forward with programming

_Cons:_
- Internet access can be spotty and the NWS API is used by requesting a URL
- Requires additional code be put onto the device, which is a different development environment
- Requires that communication be set up before a full working module is tested

**Comment by nbice** [comment]
> Do we want to query the GPS location on the AUGER device or the mobile phone?
> 
> **Mobile Phone:**
> _Pros:_
> 
> * We can routinely check weather forecasts when the app starts or with a daemon
> * The code for parsing and checking the forecast will already be on the phone
> * Does not require communication to be set up to get a fully working module
> 
> _Cons:_
> 
> * Phone is a personal device, so could be taken anywhere; therefore, we could be unnecessarily warning the user
> * Daemon will take slightly more work and research
> 
> **AUGER Device**
> _Pros:_
> 
> * Will get accurate weather forecasting with GPS coordinates because the device will stay in the same local area (probably)
> * Can routinely check weather forecasts as a separate process or within a update loop
> * Spawning a new process does not require additional research and should be straight forward with programming
> 
> _Cons:_
> 
> * Internet access can be spotty and the NWS API is used by requesting a URL
> * Requires additional code be put onto the device, which is a different development environment
> * Requires that communication be set up before a full working module is tested

I imagined it being on the mobile device, because the user will always have access to it and the mobile device will be easier to implement. Also just going by the pros and cons you listed for each choice, there are more cons on the UGV than the phone.
